vibrant_sources+= \
vai.cpp \
vanimation.cpp \
vanimationdata.cpp \
vanimationsession.cpp \
vapplication.cpp \
varmaturecontroller.cpp \
vaudio.cpp \
vboundingvolume.cpp \
vcamera.cpp \
vclient.cpp \
vclodmesh.cpp \
vcodemodule.cpp \
vcolor.cpp \
vconfig.cpp \
vcontroller.cpp \
vculler.cpp \
vdisplaystyle.cpp \
veffect.cpp \
venginesystem.cpp \
venginethread.cpp \
vexception.cpp \
vfile.cpp \
vfilestream.cpp \
vgfloader.cpp \
vgui.cpp \
vinput.cpp \
vinputmodifier.cpp \
vinputsystem.cpp \
vkeyframeanimationdata.cpp \
vlight.cpp \
vlog.cpp \
vmath.cpp \
vmatrix.cpp \
vmesh.cpp \
vmutex.cpp \
vnetworkendpoint.cpp \
vnetworklayer.cpp \
vnetworkstream.cpp \
vnode.cpp \
vobject.cpp \
vparticlesystem.cpp \
vpointable.cpp \
vphysics.cpp \
vquaternion.cpp \
vreader.cpp \
vrenderer.cpp \
vrenderwindow.cpp \
vrtti.cpp \
vscene.cpp \
vscenemanager.cpp \
vscenenode.cpp \
vserver.cpp \
vsimpleanimationdata.cpp \
vsocket.cpp \
vstream.cpp \
vstring.cpp \
vsystemmanager.cpp \
vtextstream.cpp \
vtexture.cpp \
vtexturecoord.cpp \
vtextureeffect.cpp \
vthread.cpp \
vtime.cpp \
vtimedupdater.cpp \
vtransform.cpp \
vunit.cpp \
vunitability.cpp \
vunitstat.cpp \
vupdatable.cpp \
vvector.cpp \
vvertex.cpp \
vvideo.cpp \
vwindowsapplication.cpp \
vwindowsaudio.cpp \
vwindowsclient.cpp \
vwindowscodemodule.cpp \
vwindowsinput.cpp \
vwindowsmutex.cpp \
vwindowsserver.cpp \
vwindowsthread.cpp \
vwindowstime.cpp \
vwindowsvideo.cpp \
vwriter.cpp \
vxmlwriter.cpp